/* Generated By:JavaCC: Do not edit this line. ShExJavaccConstants.java */
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package shex.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ShExJavaccConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int BOM = 9;
  /** RegularExpression Id. */
  int BASE = 10;
  /** RegularExpression Id. */
  int IMPORTS = 11;
  /** RegularExpression Id. */
  int PREFIX = 12;
  /** RegularExpression Id. */
  int SHAPE_CLASS = 13;
  /** RegularExpression Id. */
  int SHAPE = 14;
  /** RegularExpression Id. */
  int START = 15;
  /** RegularExpression Id. */
  int EXTERNAL = 16;
  /** RegularExpression Id. */
  int NOT = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int AND = 19;
  /** RegularExpression Id. */
  int LITERAL = 20;
  /** RegularExpression Id. */
  int IRI = 21;
  /** RegularExpression Id. */
  int BNODE = 22;
  /** RegularExpression Id. */
  int NONLITERAL = 23;
  /** RegularExpression Id. */
  int LENGTH = 24;
  /** RegularExpression Id. */
  int MINLENGTH = 25;
  /** RegularExpression Id. */
  int MAXLENGTH = 26;
  /** RegularExpression Id. */
  int MININCLUSIVE = 27;
  /** RegularExpression Id. */
  int MINEXCLUSIVE = 28;
  /** RegularExpression Id. */
  int MAXINCLUSIVE = 29;
  /** RegularExpression Id. */
  int MAXEXCLUSIVE = 30;
  /** RegularExpression Id. */
  int TOTALDIGITS = 31;
  /** RegularExpression Id. */
  int FRACTIONDIGITS = 32;
  /** RegularExpression Id. */
  int CLOSED = 33;
  /** RegularExpression Id. */
  int EXTRA = 34;
  /** RegularExpression Id. */
  int RDF_TYPE = 35;
  /** RegularExpression Id. */
  int CODE = 36;
  /** RegularExpression Id. */
  int REPEAT_RANGE = 37;
  /** RegularExpression Id. */
  int TRUE = 38;
  /** RegularExpression Id. */
  int FALSE = 39;
  /** RegularExpression Id. */
  int HEX = 40;
  /** RegularExpression Id. */
  int PLUS = 41;
  /** RegularExpression Id. */
  int MINUS = 42;
  /** RegularExpression Id. */
  int VBAR = 43;
  /** RegularExpression Id. */
  int AT = 44;
  /** RegularExpression Id. */
  int CARAT = 45;
  /** RegularExpression Id. */
  int DOT = 46;
  /** RegularExpression Id. */
  int BANG = 47;
  /** RegularExpression Id. */
  int QMARK = 48;
  /** RegularExpression Id. */
  int SLASH = 49;
  /** RegularExpression Id. */
  int STAR = 50;
  /** RegularExpression Id. */
  int EQUALS = 51;
  /** RegularExpression Id. */
  int LPAREN = 52;
  /** RegularExpression Id. */
  int RPAREN = 53;
  /** RegularExpression Id. */
  int LBRACE = 54;
  /** RegularExpression Id. */
  int RBRACE = 55;
  /** RegularExpression Id. */
  int LBRACKET = 56;
  /** RegularExpression Id. */
  int RBRACKET = 57;
  /** RegularExpression Id. */
  int PERCENT_CHAR = 58;
  /** RegularExpression Id. */
  int COMMA = 59;
  /** RegularExpression Id. */
  int COLON = 60;
  /** RegularExpression Id. */
  int SEMI_COLON = 61;
  /** RegularExpression Id. */
  int DOLLAR = 62;
  /** RegularExpression Id. */
  int TILDE = 63;
  /** RegularExpression Id. */
  int AMP = 64;
  /** RegularExpression Id. */
  int UCHAR = 65;
  /** RegularExpression Id. */
  int IRIref = 66;
  /** RegularExpression Id. */
  int PNAME_NS = 67;
  /** RegularExpression Id. */
  int PNAME_LN = 68;
  /** RegularExpression Id. */
  int ATPNAME_NS = 69;
  /** RegularExpression Id. */
  int ATPNAME_LN = 70;
  /** RegularExpression Id. */
  int QUOTE_3D = 71;
  /** RegularExpression Id. */
  int QUOTE_3S = 72;
  /** RegularExpression Id. */
  int ECHAR = 73;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 74;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 75;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 76;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 77;
  /** RegularExpression Id. */
  int LANG_STRING_LITERAL1 = 78;
  /** RegularExpression Id. */
  int LANG_STRING_LITERAL2 = 79;
  /** RegularExpression Id. */
  int LANG_STRING_LITERAL_LONG1 = 80;
  /** RegularExpression Id. */
  int LANG_STRING_LITERAL_LONG2 = 81;
  /** RegularExpression Id. */
  int DIGITS = 82;
  /** RegularExpression Id. */
  int INTEGER = 83;
  /** RegularExpression Id. */
  int DECIMAL = 84;
  /** RegularExpression Id. */
  int DOUBLE = 85;
  /** RegularExpression Id. */
  int EXPONENT = 86;
  /** RegularExpression Id. */
  int REGEXP = 87;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 88;
  /** RegularExpression Id. */
  int LANGTAG = 89;
  /** RegularExpression Id. */
  int A2Z = 90;
  /** RegularExpression Id. */
  int A2ZN = 91;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 92;
  /** RegularExpression Id. */
  int PN_CHARS_U = 93;
  /** RegularExpression Id. */
  int PN_CHARS = 94;
  /** RegularExpression Id. */
  int PN_PREFIX = 95;
  /** RegularExpression Id. */
  int PN_LOCAL = 96;
  /** RegularExpression Id. */
  int VARNAME = 97;
  /** RegularExpression Id. */
  int PN_LOCAL_ESC = 98;
  /** RegularExpression Id. */
  int PLX = 99;
  /** RegularExpression Id. */
  int PERCENT = 100;
  /** RegularExpression Id. */
  int UNKNOWN = 101;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "\"^^\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"\\ufeff\"",
    "\"BASE\"",
    "\"IMPORTS\"",
    "\"PREFIX\"",
    "\"shapeClass\"",
    "\"shape\"",
    "\"start\"",
    "\"external\"",
    "\"not\"",
    "\"or\"",
    "\"and\"",
    "\"literal\"",
    "\"iri\"",
    "\"bnode\"",
    "\"nonliteral\"",
    "\"length\"",
    "\"minlength\"",
    "\"maxlength\"",
    "\"mininclusive\"",
    "\"minexclusive\"",
    "\"maxinclusive\"",
    "\"maxexclusive\"",
    "\"totaldigits\"",
    "\"fractiondigits\"",
    "\"closed\"",
    "\"extra\"",
    "\"a\"",
    "<CODE>",
    "<REPEAT_RANGE>",
    "\"true\"",
    "\"false\"",
    "<HEX>",
    "\"+\"",
    "\"-\"",
    "\"|\"",
    "\"@\"",
    "\"^\"",
    "\".\"",
    "\"!\"",
    "\"?\"",
    "\"/\"",
    "\"*\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"%\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"$\"",
    "\"~\"",
    "\"&\"",
    "<UCHAR>",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<ATPNAME_NS>",
    "<ATPNAME_LN>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "<LANG_STRING_LITERAL1>",
    "<LANG_STRING_LITERAL2>",
    "<LANG_STRING_LITERAL_LONG1>",
    "<LANG_STRING_LITERAL_LONG2>",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "<REGEXP>",
    "<BLANK_NODE_LABEL>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<PN_LOCAL_ESC>",
    "<PLX>",
    "<PERCENT>",
    "<UNKNOWN>",
  };

}
