/* Generated By:JavaCC: Do not edit this line. ShExJavaccConstants.java */
/**
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package shex.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ShExJavaccConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BOM = 12;
  /** RegularExpression Id. */
  int BASE = 13;
  /** RegularExpression Id. */
  int IMPORT = 14;
  /** RegularExpression Id. */
  int PREFIX = 15;
  /** RegularExpression Id. */
  int SHAPE_CLASS = 16;
  /** RegularExpression Id. */
  int SHAPE = 17;
  /** RegularExpression Id. */
  int START = 18;
  /** RegularExpression Id. */
  int EXTERNAL = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int LITERAL = 23;
  /** RegularExpression Id. */
  int IRI = 24;
  /** RegularExpression Id. */
  int BNODE = 25;
  /** RegularExpression Id. */
  int NONLITERAL = 26;
  /** RegularExpression Id. */
  int LENGTH = 27;
  /** RegularExpression Id. */
  int MINLENGTH = 28;
  /** RegularExpression Id. */
  int MAXLENGTH = 29;
  /** RegularExpression Id. */
  int MININCLUSIVE = 30;
  /** RegularExpression Id. */
  int MINEXCLUSIVE = 31;
  /** RegularExpression Id. */
  int MAXINCLUSIVE = 32;
  /** RegularExpression Id. */
  int MAXEXCLUSIVE = 33;
  /** RegularExpression Id. */
  int TOTALDIGITS = 34;
  /** RegularExpression Id. */
  int FRACTIONDIGITS = 35;
  /** RegularExpression Id. */
  int CLOSED = 36;
  /** RegularExpression Id. */
  int EXTRA = 37;
  /** RegularExpression Id. */
  int RDF_TYPE = 38;
  /** RegularExpression Id. */
  int CODE = 39;
  /** RegularExpression Id. */
  int REPEAT_RANGE = 40;
  /** RegularExpression Id. */
  int TRUE = 41;
  /** RegularExpression Id. */
  int FALSE = 42;
  /** RegularExpression Id. */
  int HEX = 43;
  /** RegularExpression Id. */
  int PLUS = 44;
  /** RegularExpression Id. */
  int MINUS = 45;
  /** RegularExpression Id. */
  int VBAR = 46;
  /** RegularExpression Id. */
  int AT = 47;
  /** RegularExpression Id. */
  int CARAT = 48;
  /** RegularExpression Id. */
  int DOT = 49;
  /** RegularExpression Id. */
  int BANG = 50;
  /** RegularExpression Id. */
  int QMARK = 51;
  /** RegularExpression Id. */
  int SLASH = 52;
  /** RegularExpression Id. */
  int STAR = 53;
  /** RegularExpression Id. */
  int EQUALS = 54;
  /** RegularExpression Id. */
  int LPAREN = 55;
  /** RegularExpression Id. */
  int RPAREN = 56;
  /** RegularExpression Id. */
  int LBRACE = 57;
  /** RegularExpression Id. */
  int RBRACE = 58;
  /** RegularExpression Id. */
  int LBRACKET = 59;
  /** RegularExpression Id. */
  int RBRACKET = 60;
  /** RegularExpression Id. */
  int PERCENT_CHAR = 61;
  /** RegularExpression Id. */
  int COMMA = 62;
  /** RegularExpression Id. */
  int SEMI_COLON = 63;
  /** RegularExpression Id. */
  int DOLLAR = 64;
  /** RegularExpression Id. */
  int TILDE = 65;
  /** RegularExpression Id. */
  int AMP = 66;
  /** RegularExpression Id. */
  int UCHAR = 67;
  /** RegularExpression Id. */
  int IRIref = 68;
  /** RegularExpression Id. */
  int PNAME_NS = 69;
  /** RegularExpression Id. */
  int PNAME_LN = 70;
  /** RegularExpression Id. */
  int ATPNAME_NS = 71;
  /** RegularExpression Id. */
  int ATPNAME_LN = 72;
  /** RegularExpression Id. */
  int QUOTE_3D = 73;
  /** RegularExpression Id. */
  int QUOTE_3S = 74;
  /** RegularExpression Id. */
  int ECHAR = 75;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 76;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 77;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 78;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 79;
  /** RegularExpression Id. */
  int LANG_STRING_LITERAL1 = 80;
  /** RegularExpression Id. */
  int LANG_STRING_LITERAL2 = 81;
  /** RegularExpression Id. */
  int LANG_STRING_LITERAL_LONG1 = 82;
  /** RegularExpression Id. */
  int LANG_STRING_LITERAL_LONG2 = 83;
  /** RegularExpression Id. */
  int DIGITS = 84;
  /** RegularExpression Id. */
  int INTEGER = 85;
  /** RegularExpression Id. */
  int DECIMAL = 86;
  /** RegularExpression Id. */
  int DOUBLE = 87;
  /** RegularExpression Id. */
  int EXPONENT = 88;
  /** RegularExpression Id. */
  int REGEXP = 89;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 90;
  /** RegularExpression Id. */
  int LANGTAG = 91;
  /** RegularExpression Id. */
  int A2Z = 92;
  /** RegularExpression Id. */
  int A2ZN = 93;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 94;
  /** RegularExpression Id. */
  int PN_CHARS_U = 95;
  /** RegularExpression Id. */
  int PN_CHARS = 96;
  /** RegularExpression Id. */
  int PN_PREFIX = 97;
  /** RegularExpression Id. */
  int PN_LOCAL = 98;
  /** RegularExpression Id. */
  int VARNAME = 99;
  /** RegularExpression Id. */
  int PN_LOCAL_ESC = 100;
  /** RegularExpression Id. */
  int PLX = 101;
  /** RegularExpression Id. */
  int PERCENT = 102;
  /** RegularExpression Id. */
  int UNKNOWN = 103;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "\"^^\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 8>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"\\ufeff\"",
    "\"BASE\"",
    "\"IMPORT\"",
    "\"PREFIX\"",
    "\"shapeClass\"",
    "\"shape\"",
    "\"start\"",
    "\"external\"",
    "\"not\"",
    "\"or\"",
    "\"and\"",
    "\"literal\"",
    "\"iri\"",
    "\"bnode\"",
    "\"nonliteral\"",
    "\"length\"",
    "\"minlength\"",
    "\"maxlength\"",
    "\"mininclusive\"",
    "\"minexclusive\"",
    "\"maxinclusive\"",
    "\"maxexclusive\"",
    "\"totaldigits\"",
    "\"fractiondigits\"",
    "\"closed\"",
    "\"extra\"",
    "\"a\"",
    "<CODE>",
    "<REPEAT_RANGE>",
    "\"true\"",
    "\"false\"",
    "<HEX>",
    "\"+\"",
    "\"-\"",
    "\"|\"",
    "\"@\"",
    "\"^\"",
    "\".\"",
    "\"!\"",
    "\"?\"",
    "\"/\"",
    "\"*\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"%\"",
    "\",\"",
    "\";\"",
    "\"$\"",
    "\"~\"",
    "\"&\"",
    "<UCHAR>",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<ATPNAME_NS>",
    "<ATPNAME_LN>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "<LANG_STRING_LITERAL1>",
    "<LANG_STRING_LITERAL2>",
    "<LANG_STRING_LITERAL_LONG1>",
    "<LANG_STRING_LITERAL_LONG2>",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "<REGEXP>",
    "<BLANK_NODE_LABEL>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<PN_LOCAL_ESC>",
    "<PLX>",
    "<PERCENT>",
    "<UNKNOWN>",
  };

}
